/*
 * Generated by compile_query.py
 */
#ifndef __SCHEMA_netflow_H__
#define __SCHEMA_netflow_H__

#include "graph.hpp"

struct NetflowAttbs {
    int src_port;
    // time_t timestamp;
    int num_bytes;
    int num_packets;
    int dst_port;
    float duration;
    bool FilterEdge(int edge_id) const;
};

typedef Graph<Label,NetflowAttbs> StreamG;

#endif
